import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Loader2, RefreshCw, Save, Users } from 'lucide-react';
import apiClient from '@/api/apiClient';
import { toast } from 'sonner';

type Section={id:string;name:string;class?:{name?:string}};
type Row={studentId:string;name:string;rollNo?:string|null;admissionNo?:string|null;status:'PRESENT'|'ABSENT'|'LATE'|'LEAVE';remarks?:string};
const statuses=['PRESENT','ABSENT','LATE','LEAVE'] as const;
export default function AttendanceLive(){
 const [sections,setSections]=useState<Section[]>([]),[sectionId,setSectionId]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const loadSections=async()=>{try{const {data}=await apiClient.get('/academics/sections');const list=Array.isArray(data)?data:[];setSections(list);if(!sectionId&&list[0])setSectionId(list[0].id)}catch(e:any){toast.error(e?.response?.data?.message||'Unable to load sections')}finally{setLoading(false)}};
 const load=async()=>{if(!sectionId)return;try{setLoading(true);const {data}=await apiClient.get('/attendance',{params:{sectionId,date}});setRows(Array.isArray(data)?data:[])}catch(e:any){toast.error(e?.response?.data?.message||'Unable to load attendance');setRows([])}finally{setLoading(false)}};
 useEffect(()=>{loadSections()},[]); useEffect(()=>{if(sectionId)load()},[sectionId,date]);
 const setAll=(status:Row['status'])=>setRows(r=>r.map(x=>({...x,status})));
 const save=async()=>{if(!sectionId||!rows.length)return;setSaving(true);try{await apiClient.post('/attendance',{sectionId,date,records:rows.map(r=>({studentId:r.studentId,status:r.status,remarks:r.remarks||''}))});toast.success('Attendance saved successfully')}catch(e:any){toast.error(e?.response?.data?.message||'Failed to save attendance')}finally{setSaving(false)}};
 const counts=useMemo(()=>({present:rows.filter(r=>r.status==='PRESENT').length,absent:rows.filter(r=>r.status==='ABSENT').length,late:rows.filter(r=>r.status==='LATE').length,leave:rows.filter(r=>r.status==='LEAVE').length}),[rows]);
 if(loading&&!rows.length)return <div className="min-h-[50vh] flex items-center justify-center"><Loader2 className="animate-spin text-primary"/></div>;
 return <div className="space-y-6 pb-10"><div className="rounded-[28px] border border-border bg-card p-6 shadow-xl"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-primary">Student Management</div><h1 className="text-3xl font-black mt-2">Attendance</h1><p className="text-sm text-muted-foreground mt-1">Live daily attendance with database-backed records.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-border px-4 py-2.5 text-sm font-bold"><RefreshCw size={16} className="inline mr-2"/>Refresh</button><button onClick={save} disabled={saving||!rows.length} className="rounded-xl bg-primary text-primary-foreground px-4 py-2.5 text-sm font-bold"><Save size={16} className="inline mr-2"/>{saving?'Saving...':'Save Attendance'}</button></div></div></div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3"><select value={sectionId} onChange={e=>setSectionId(e.target.value)} className="rounded-xl border border-border bg-card px-4 py-3 text-sm"><option value="">Select section</option>{sections.map(s=><option key={s.id} value={s.id}>{s.class?.name?`${s.class.name} • `:''}{s.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border border-border bg-card px-4 py-3 text-sm"/><button onClick={()=>setAll('PRESENT')} className="rounded-xl border border-border bg-card px-4 py-3 text-sm font-bold">Mark All Present</button><div className="rounded-xl border border-border bg-card px-4 py-3 text-sm"><b>{counts.present}</b> Present · <b>{counts.absent}</b> Absent</div><div className="rounded-xl border border-border bg-card px-4 py-3 text-sm"><b>{counts.late}</b> Late · <b>{counts.leave}</b> Leave</div></div>
 <div className="rounded-3xl border border-border bg-card overflow-hidden"><div className="p-4 border-b border-border flex items-center gap-2 font-black"><Users size={18}/> {rows.length} Students</div>{rows.length?<div className="divide-y divide-border">{rows.map(r=><div key={r.studentId} className="p-4 flex flex-col md:flex-row md:items-center gap-3"><div className="flex-1"><p className="font-bold">{r.name}</p><p className="text-xs text-muted-foreground">Roll: {r.rollNo||'—'} · Admission: {r.admissionNo||'—'}</p></div><div className="flex flex-wrap gap-2">{statuses.map(s=><button key={s} onClick={()=>setRows(p=>p.map(x=>x.studentId===r.studentId?{...x,status:s}:x))} className={`rounded-lg px-3 py-2 text-xs font-black ${r.status===s?'bg-primary text-primary-foreground':'border border-border bg-background text-muted-foreground'}`}>{s}</button>)}</div><input value={r.remarks||''} onChange={e=>setRows(p=>p.map(x=>x.studentId===r.studentId?{...x,remarks:e.target.value}:x))} placeholder="Remarks" className="md:w-48 rounded-lg border border-border bg-background px-3 py-2 text-sm"/></div>)}</div>:<div className="p-12 text-center text-sm text-muted-foreground"><CheckCircle2 className="mx-auto mb-3 opacity-40"/>No students found for this section.</div>}</div></div>;
}