import React, { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowRight, Bell, BookOpen, CalendarDays, DollarSign, GraduationCap, Loader2, RefreshCw, Users } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import apiClient from '@/api/apiClient';
import { toast } from 'sonner';

type Stats = { studentsCount?: number; teachersCount?: number; parentsCount?: number; staffCount?: number; classesCount?: number; todayAttendancePercentage?: number; totalRevenue?: number; pendingFees?: number; pendingFeePaymentsCount?: number; pendingHomeworks?: number; pendingLeaves?: number; overdueLibraryBooks?: number; announcements?: any[]; recentAdmissions?: any[]; upcomingExams?: any[] };

export default function Dashboard() {
  const { user } = useAuth(); const { schoolSlug } = useParams(); const base = schoolSlug ? `/${schoolSlug}` : '';
  const [stats, setStats] = useState<Stats | null>(null); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const r = await apiClient.get('/people/stats'); setStats(r.data || {}); } catch (e: any) { toast.error(e?.response?.data?.message || 'Unable to load dashboard'); setStats(null); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const cards = useMemo(() => [['Students', stats?.studentsCount ?? 0, GraduationCap], ['Teachers', stats?.teachersCount ?? 0, Users], ['Staff', stats?.staffCount ?? 0, Users], ['Classes', stats?.classesCount ?? 0, BookOpen], ['Attendance Today', `${stats?.todayAttendancePercentage ?? 0}%`, Activity], ['Collected', `PKR ${Number(stats?.totalRevenue ?? 0).toLocaleString()}`, DollarSign]], [stats]);
  if (loading) return <div className="py-16 flex justify-center"><Loader2 className="animate-spin"/></div>;
  return <div className="space-y-6"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-muted-foreground">{user?.schoolName || 'School'}</p><h1 className="text-3xl font-bold mt-1">Dashboard</h1><p className="text-sm text-muted-foreground mt-1">Live overview from your school's database.</p></div><button onClick={load} className="px-4 py-2 rounded-lg border flex items-center gap-2 w-fit"><RefreshCw size={16}/> Refresh</button></div>
    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">{cards.map(([label,value,Icon]) => <div key={String(label)} className="rounded-xl border p-4"><Icon size={18} className="text-primary mb-3"/><div className="text-xl font-bold">{String(value)}</div><div className="text-xs text-muted-foreground mt-1">{label}</div></div>)}</div>
    <div className="grid lg:grid-cols-3 gap-4"><div className="lg:col-span-2 rounded-xl border p-5"><div className="flex items-center justify-between mb-4"><h2 className="font-semibold">Recent Admissions</h2><Link to={`${base}/students`} className="text-sm text-primary flex items-center gap-1">View all <ArrowRight size={14}/></Link></div>{(stats?.recentAdmissions || []).length === 0 ? <p className="text-sm text-muted-foreground">No recent admissions.</p> : <div className="divide-y">{stats?.recentAdmissions?.slice(0,8).map((s: any, i: number) => <div key={s.id || i} className="py-3 flex justify-between gap-3"><div><div className="font-medium">{s.name}</div><div className="text-xs text-muted-foreground">{s.admissionNo || 'Admission'}{s.section?.name ? ` · ${s.section.name}` : ''}</div></div><span className="text-xs text-muted-foreground">{s.admissionDate ? new Date(s.admissionDate).toLocaleDateString() : ''}</span></div>)}</div>}</div>
      <div className="rounded-xl border p-5"><h2 className="font-semibold mb-4">School Activity</h2><div className="space-y-3 text-sm"><div className="flex justify-between"><span>Pending fees</span><b>PKR {Number(stats?.pendingFees ?? 0).toLocaleString()}</b></div><div className="flex justify-between"><span>Pending fee records</span><b>{stats?.pendingFeePaymentsCount ?? 0}</b></div><div className="flex justify-between"><span>Pending homework</span><b>{stats?.pendingHomeworks ?? 0}</b></div><div className="flex justify-between"><span>Pending leaves</span><b>{stats?.pendingLeaves ?? 0}</b></div><div className="flex justify-between"><span>Overdue library books</span><b>{stats?.overdueLibraryBooks ?? 0}</b></div></div></div></div>
    <div className="grid lg:grid-cols-2 gap-4"><div className="rounded-xl border p-5"><h2 className="font-semibold flex items-center gap-2 mb-4"><Bell size={18}/> Announcements</h2>{(stats?.announcements || []).length === 0 ? <p className="text-sm text-muted-foreground">No announcements.</p> : <div className="space-y-3">{stats?.announcements?.slice(0,6).map((a: any) => <div key={a.id} className="border-b last:border-0 pb-3"><div className="font-medium">{a.title}</div><div className="text-xs text-muted-foreground mt-1">{a.publishedAt ? new Date(a.publishedAt).toLocaleString() : ''}</div></div>)}</div>}</div><div className="rounded-xl border p-5"><h2 className="font-semibold flex items-center gap-2 mb-4"><CalendarDays size={18}/> Upcoming Exams</h2>{(stats?.upcomingExams || []).length === 0 ? <p className="text-sm text-muted-foreground">No upcoming exams.</p> : <div className="space-y-3">{stats?.upcomingExams?.slice(0,6).map((e: any) => <div key={e.id} className="border-b last:border-0 pb-3"><div className="font-medium">{e.name}</div><div className="text-xs text-muted-foreground mt-1">{e.startDate ? new Date(e.startDate).toLocaleDateString() : ''} · {e.type || 'Exam'}</div></div>)}</div>}</div></div>
  </div>;
}
