import { useEffect, useMemo, useState } from 'react';
import { Calendar, CheckCircle2, Loader2, Plus, RefreshCw, Search, Upload, X } from 'lucide-react';
import apiClient from '@/api/apiClient';
import { toast } from 'sonner';

interface Exam { id: string; name: string; type?: string; startDate: string; endDate: string; totalMarks: number; passingMarks: number; sectionId?: string | null; isPublished?: boolean; description?: string | null; }
interface Section { id: string; name: string; class?: { name?: string } }
interface Subject { id: string; name: string }
interface Student { id: string; name: string; rollNo?: string | null; sectionId?: string | null }

const TYPES = ['UNIT_TEST','MONTHLY_TEST','MIDTERM','FINAL','QUIZ','MOCK_BOARD'];

export default function ExamsLive() {
  const [exams,setExams]=useState<Exam[]>([]); const [sections,setSections]=useState<Section[]>([]); const [subjects,setSubjects]=useState<Subject[]>([]); const [students,setStudents]=useState<Student[]>([]);
  const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [search,setSearch]=useState(''); const [selected,setSelected]=useState<Exam|null>(null); const [showCreate,setShowCreate]=useState(false); const [saving,setSaving]=useState(false); const [resultSaving,setResultSaving]=useState(false);
  const [form,setForm]=useState({name:'',type:'UNIT_TEST',startDate:'',endDate:'',totalMarks:'100',passingMarks:'33',sectionId:'',description:''});
  const [subjectId,setSubjectId]=useState(''); const [resultRows,setResultRows]=useState<Record<string,string>>({});

  const load=async()=>{ try { const [e,s,sub,st]=await Promise.all([apiClient.get('/exams'),apiClient.get('/academics/sections'),apiClient.get('/academics/subjects'),apiClient.get('/people/students')]); setExams(Array.isArray(e.data)?e.data:[]); setSections(Array.isArray(s.data)?s.data:[]); setSubjects(Array.isArray(sub.data)?sub.data:[]); setStudents(Array.isArray(st.data)?st.data:[]); } catch(err:any){ toast.error(err?.response?.data?.message || 'Unable to load exam data'); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>exams.filter(e=>`${e.name} ${e.type||''}`.toLowerCase().includes(search.toLowerCase())),[exams,search]);
  const create=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const {data}=await apiClient.post('/exams',{...form,totalMarks:Number(form.totalMarks),passingMarks:Number(form.passingMarks),sectionId:form.sectionId||undefined});setExams(p=>[data,...p]);setSelected(data);setShowCreate(false);setForm({name:'',type:'UNIT_TEST',startDate:'',endDate:'',totalMarks:'100',passingMarks:'33',sectionId:'',description:''});toast.success('Exam created');}catch(err:any){toast.error(err?.response?.data?.message||'Failed to create exam')}finally{setSaving(false)}};
  const publish=async(exam:Exam)=>{try{const {data}=await apiClient.patch(`/exams/${exam.id}/publish`,{published:!exam.isPublished});setExams(p=>p.map(x=>x.id===exam.id?data:x));setSelected(data);toast.success(data.isPublished?'Exam published':'Exam unpublished')}catch(err:any){toast.error(err?.response?.data?.message||'Unable to update publication status')}};
  const loadResults=async()=>{if(!selected||!subjectId)return;try{const {data}=await apiClient.get('/exams/results',{params:{examId:selected.id,subjectId}});const next:Record<string,string>={};(Array.isArray(data)?data:[]).forEach((r:any)=>{next[r.studentId]=String(r.marksObtained??'')});setResultRows(next)}catch(err:any){toast.error(err?.response?.data?.message||'Unable to load results')}};
  const saveResults=async()=>{if(!selected||!subjectId)return;setResultSaving(true);try{await apiClient.post('/exams/results',{examId:selected.id,results:Object.entries(resultRows).filter(([,v])=>v!=='').map(([studentId,v])=>({studentId,subjectId,marksObtained:Number(v),isAbsent:false}))});toast.success('Results saved');}catch(err:any){toast.error(err?.response?.data?.message||'Failed to save results')}finally{setResultSaving(false)}};
  const sectionStudents=selected?.sectionId?students.filter(s=>s.sectionId===selected.sectionId):students;

  if(loading)return <div className="min-h-[50vh] flex items-center justify-center"><Loader2 className="animate-spin text-primary"/></div>;
  return <div className="space-y-6 pb-10">
    <div className="rounded-[28px] border border-border bg-card p-6 shadow-xl"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-primary">Academic Management</p><h1 className="text-3xl font-black mt-2">Exams & Results</h1><p className="text-sm text-muted-foreground mt-1">Live exam schedules, publication and result entry.</p></div><div className="flex gap-2"><button onClick={()=>{setRefreshing(true);load()}} className="rounded-xl border border-border px-4 py-2.5 font-bold text-sm"><RefreshCw size={16} className="inline mr-2"/>Refresh</button><button onClick={()=>setShowCreate(true)} className="rounded-xl bg-primary text-primary-foreground px-4 py-2.5 font-bold text-sm"><Plus size={16} className="inline mr-2"/>Create Exam</button></div></div></div>
    <div className="rounded-2xl border border-border bg-card p-3 flex items-center gap-2"><Search size={17} className="text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search exams..." className="w-full bg-transparent outline-none text-sm"/></div>
    <div className="grid lg:grid-cols-[.9fr_1.1fr] gap-5"><div className="space-y-3">{filtered.map(ex=><button key={ex.id} onClick={()=>{setSelected(ex);setSubjectId('');setResultRows({})}} className={`w-full text-left rounded-2xl border p-4 transition ${selected?.id===ex.id?'border-primary bg-primary/5':'border-border bg-card hover:border-primary/30'}`}><div className="flex justify-between gap-3"><div><h2 className="font-black">{ex.name}</h2><p className="text-xs text-muted-foreground mt-1">{ex.type||'Exam'} • {new Date(ex.startDate).toLocaleDateString()} – {new Date(ex.endDate).toLocaleDateString()}</p></div><span className={`text-[10px] font-black uppercase ${ex.isPublished?'text-emerald-500':'text-amber-500'}`}>{ex.isPublished?'Published':'Draft'}</span></div></button>)}{!filtered.length&&<div className="rounded-2xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No exams found.</div>}</div>
      <div className="rounded-3xl border border-border bg-card p-6 min-h-[360px]">{selected?<><div className="flex justify-between gap-4"><div><h2 className="text-2xl font-black">{selected.name}</h2><p className="text-sm text-muted-foreground mt-1">{selected.totalMarks} marks • Passing {selected.passingMarks}</p></div><button onClick={()=>publish(selected)} className="rounded-xl border border-border px-4 py-2 text-sm font-bold">{selected.isPublished?'Unpublish':'Publish'}</button></div><div className="mt-6 border-t border-border pt-5"><div className="flex flex-col sm:flex-row gap-3"><select value={subjectId} onChange={e=>setSubjectId(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-2 text-sm"><option value="">Select subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button onClick={loadResults} disabled={!subjectId} className="rounded-xl bg-primary text-primary-foreground px-4 py-2 text-sm font-bold">Load Results</button></div><div className="mt-4 max-h-72 overflow-auto space-y-2">{sectionStudents.map(st=><div key={st.id} className="flex items-center gap-3 rounded-xl bg-background/60 p-3"><div className="flex-1"><p className="text-sm font-bold">{st.name}</p><p className="text-[11px] text-muted-foreground">Roll No: {st.rollNo||'—'}</p></div><input type="number" min="0" max={selected.totalMarks} value={resultRows[st.id]||''} onChange={e=>setResultRows(p=>({...p,[st.id]:e.target.value}))} disabled={selected.isPublished} placeholder="Marks" className="w-28 rounded-lg border border-border bg-background px-3 py-2 text-sm"/></div>)}</div>{sectionStudents.length>0&&<button onClick={saveResults} disabled={selected.isPublished||resultSaving||!subjectId} className="mt-4 rounded-xl bg-primary text-primary-foreground px-5 py-2.5 text-sm font-bold disabled:opacity-50">{resultSaving?'Saving...':'Save Results'}</button>}</div></>:<div className="h-full flex items-center justify-center text-sm text-muted-foreground">Select an exam to manage it.</div>}</div></div>
    {showCreate&&<div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm p-4 flex items-center justify-center"><form onSubmit={create} className="w-full max-w-2xl rounded-3xl border border-border bg-card p-6 space-y-4"><div className="flex justify-between"><h2 className="text-xl font-black">Create Exam</h2><button type="button" onClick={()=>setShowCreate(false)}><X/></button></div><input required placeholder="Exam name" value={form.name} onChange={e=>setForm(p=>({...p,name:e.target.value}))} className="w-full rounded-xl border border-border bg-background px-4 py-3"/><div className="grid sm:grid-cols-2 gap-3"><select value={form.type} onChange={e=>setForm(p=>({...p,type:e.target.value}))} className="rounded-xl border border-border bg-background px-4 py-3">{TYPES.map(t=><option key={t}>{t}</option>)}</select><select value={form.sectionId} onChange={e=>setForm(p=>({...p,sectionId:e.target.value}))} className="rounded-xl border border-border bg-background px-4 py-3"><option value="">All sections</option>{sections.map(s=><option key={s.id} value={s.id}>{s.class?.name?`${s.class.name} • `:''}{s.name}</option>)}</select><input required type="date" value={form.startDate} onChange={e=>setForm(p=>({...p,startDate:e.target.value}))} className="rounded-xl border border-border bg-background px-4 py-3"/><input required type="date" value={form.endDate} onChange={e=>setForm(p=>({...p,endDate:e.target.value}))} className="rounded-xl border border-border bg-background px-4 py-3"/><input type="number" min="1" value={form.totalMarks} onChange={e=>setForm(p=>({...p,totalMarks:e.target.value}))} className="rounded-xl border border-border bg-background px-4 py-3"/><input type="number" min="0" value={form.passingMarks} onChange={e=>setForm(p=>({...p,passingMarks:e.target.value}))} className="rounded-xl border border-border bg-background px-4 py-3"/></div><textarea placeholder="Description (optional)" value={form.description} onChange={e=>setForm(p=>({...p,description:e.target.value}))} className="w-full rounded-xl border border-border bg-background px-4 py-3"/><button disabled={saving} className="w-full rounded-xl bg-primary text-primary-foreground py-3 font-black">{saving?'Creating...':'Create Exam'}</button></form></div>}
  </div>;
}
