import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Check, Crown, GraduationCap, Menu, Search, ShieldCheck, Star, Users, WalletCards, X, Zap } from 'lucide-react';
import apiClient from '@/api/apiClient';
import SchoolSearchModal from '@/component/SchoolSearchModal';

type PublicPlan = { id: string; planKey: string; name: string; price: number; period: string; features: string[] };
const fallbackPlans: PublicPlan[] = [
  { id: 'free-trial', planKey: 'FREE_TRIAL', name: 'Free Trial', price: 0, period: '1 day', features: ['Up to 20 students', 'Attendance & fees', 'Exams & results', 'Basic reports'] },
  { id: 'professional', planKey: 'PROFESSIONAL', name: 'Professional', price: 3000, period: 'per month', features: ['Up to 500 students', 'Unlimited staff', 'All school modules', 'Advanced reports', 'Priority support'] },
  { id: 'premium', planKey: 'PREMIUM', name: 'Premium', price: 5000, period: 'per month', features: ['Unlimited students', 'Unlimited staff', 'All modules', 'Advanced reports', 'Custom domain ready'] },
];
const modules = [
  ['Academics', 'Classes, subjects, timetable, homework and digital learning.'], ['Attendance', 'Fast daily attendance with clear student and staff records.'], ['Exams & Results', 'Exams, marks, grades, result cards and performance reports.'], ['Fees & Finance', 'Fee structures, payments, receipts and finance reporting.'], ['Teachers & Staff', 'Staff records, attendance and school operations.'], ['Transport', 'Routes, vehicles, drivers and student assignments.'], ['Communication', 'Announcements, notifications and school-wide updates.'], ['Reports', 'Actionable reports for school leadership and administrators.'],
];
const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });

export default function LandingPage() {
  const navigate = useNavigate();
  const [searchOpen, setSearchOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [plans, setPlans] = useState<PublicPlan[]>(fallbackPlans);

  useEffect(() => {
    apiClient.get('/public/plans').then((res) => {
      const data = Array.isArray(res.data) ? res.data : [];
      if (data.length) setPlans(data.map((p: any) => ({ ...p, features: Array.isArray(p.features) ? p.features : [] })));
    }).catch(() => undefined);
  }, []);

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#06111d] font-sans text-white">
      <div className="pointer-events-none fixed inset-0 -z-10 overflow-hidden bg-[#06111d]"><div className="absolute -left-40 -top-40 h-[620px] w-[620px] rounded-full bg-cyan-500/10 blur-[120px]" /><div className="absolute right-[-180px] top-[18%] h-[650px] w-[650px] rounded-full bg-indigo-500/10 blur-[130px]" /><div className="absolute bottom-[-220px] left-[28%] h-[600px] w-[600px] rounded-full bg-emerald-500/10 blur-[130px]" /></div>
      <nav className="fixed left-0 right-0 top-0 z-50 px-4 pt-4"><div className="mx-auto flex max-w-7xl items-center justify-between rounded-2xl border border-white/10 bg-[#071522]/90 px-4 py-3 shadow-2xl backdrop-blur-xl"><Link to="/" className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-400 to-blue-600 font-black">E</div><div><p className="font-black">EduSphere</p><p className="text-[9px] font-bold tracking-[.22em] text-cyan-300">MULTI-TENANT SAAS</p></div></Link><div className="hidden items-center gap-6 md:flex">{['Features', 'Modules', 'Pricing'].map((item) => <button key={item} onClick={() => go(item.toLowerCase())} className="text-sm font-semibold text-slate-300 hover:text-white">{item}</button>)}</div><div className="hidden items-center gap-2 md:flex"><button onClick={() => navigate('/admin-login')} className="flex items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-500/10 px-3.5 py-2.5 text-xs font-bold text-violet-200"><ShieldCheck size={14} /> Super Admin</button><button onClick={() => setSearchOpen(true)} className="flex items-center gap-2 rounded-xl border border-white/10 px-3.5 py-2.5 text-xs font-bold text-slate-200"><Search size={14} /> School Login</button><button onClick={() => go('pricing')} className="rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-4 py-2.5 text-xs font-black">Register School</button></div><button onClick={() => setMenuOpen((v) => !v)} className="rounded-xl border border-white/10 p-2 md:hidden">{menuOpen ? <X size={19} /> : <Menu size={19} />}</button></div>{menuOpen && <div className="mx-4 mt-2 rounded-2xl border border-white/10 bg-[#071522]/95 p-5 backdrop-blur-xl md:hidden"><div className="flex flex-col gap-3"><button onClick={() => { setMenuOpen(false); go('modules'); }}>Modules</button><button onClick={() => { setMenuOpen(false); go('pricing'); }}>Pricing</button><button onClick={() => { setMenuOpen(false); navigate('/admin-login'); }}>Super Admin</button><button onClick={() => { setMenuOpen(false); setSearchOpen(true); }}>School Login</button></div></div>}</nav>
      <main>
        <section className="relative flex min-h-screen items-center px-5 pb-20 pt-32"><div className="mx-auto grid w-full max-w-7xl items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/10 px-3.5 py-1.5 text-[10px] font-black uppercase tracking-[.18em] text-cyan-300"><span className="h-2 w-2 animate-pulse rounded-full bg-cyan-300" /> School management, redesigned</div><h1 className="max-w-4xl text-5xl font-black leading-[1.03] tracking-tight sm:text-6xl lg:text-7xl">One powerful platform for <span className="bg-gradient-to-r from-cyan-300 via-sky-400 to-indigo-400 bg-clip-text text-transparent">every school operation.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">Students, teachers, attendance, exams, fees, communication, reports and school administration in one secure multi-tenant SaaS platform.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={() => go('pricing')} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-cyan-500 to-blue-600 px-6 py-4 text-sm font-black">Start with a Plan <ArrowRight size={16} /></button><button onClick={() => setSearchOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-6 py-4 text-sm font-black"><Search size={16} className="text-cyan-300" /> Find School Login</button></div></motion.div><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7, delay: .1 }} className="rounded-[30px] border border-white/10 bg-[#091a2a]/90 p-5 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-300">Super Admin Console</p><p className="mt-1 text-lg font-black">Platform Intelligence</p></div><WalletCards size={18} className="text-cyan-300" /></div><div className="grid grid-cols-2 gap-3 py-4">{[['Schools', ShieldCheck], ['Revenue', WalletCards], ['Students', GraduationCap], ['Staff', Users]].map(([label, Icon]: any) => <div key={label} className="rounded-2xl bg-white/[.04] p-4"><Icon size={18} className="text-cyan-300" /><p className="mt-3 text-xl font-black">{label}</p><p className="text-[10px] text-slate-500">Managed centrally</p></div>)}</div><div className="rounded-2xl border border-cyan-400/10 bg-cyan-400/5 p-4"><div className="flex justify-between text-xs font-bold text-slate-300"><span>Operational health</span><span className="text-emerald-300">LIVE</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[86%] rounded-full bg-gradient-to-r from-cyan-400 to-indigo-500" /></div></div></motion.div></div></section>
        <section id="features" className="mx-auto max-w-7xl px-5 py-20"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Fast', 'Daily workflows built for speed', Zap], ['Secure', 'Role-based access by tenant', ShieldCheck], ['Multi-school', 'One platform for every campus', GraduationCap], ['Insightful', 'Reports for better decisions', Star]].map(([title, text, Icon]: any) => <div key={title} className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><Icon size={20} className="text-cyan-300" /><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></section>
        <section id="modules" className="mx-auto max-w-7xl px-5 py-20"><div className="mb-10"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Everything in one place</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">Run the whole school.</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{modules.map(([title, text]) => <div key={title} className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></section>
        <section id="pricing" className="mx-auto max-w-7xl px-5 py-20"><div className="mb-10 text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Simple plans</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">Choose your school plan.</h2></div><div className="grid gap-5 lg:grid-cols-3">{plans.map((plan) => { const Icon = plan.planKey === 'PREMIUM' ? Crown : plan.planKey === 'PROFESSIONAL' ? Star : Zap; return <div key={plan.id} className="rounded-3xl border border-white/10 bg-[#091a2a]/90 p-6 shadow-xl"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300"><Icon size={20} /></div>{plan.planKey === 'PROFESSIONAL' && <span className="rounded-full bg-indigo-500/10 px-3 py-1 text-[10px] font-black text-indigo-300">MOST POPULAR</span>}</div><h3 className="mt-6 text-xl font-black">{plan.name}</h3><div className="mt-3"><span className="text-4xl font-black">PKR {Number(plan.price).toLocaleString()}</span><span className="ml-2 text-sm text-slate-500">{plan.period}</span></div><ul className="mt-6 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex items-start gap-2 text-sm text-slate-300"><Check size={16} className="mt-0.5 shrink-0 text-emerald-300" />{feature}</li>)}</ul><button onClick={() => { sessionStorage.setItem('edusphere_registration_plan', plan.planKey); navigate(`/register-school/form?plan=${encodeURIComponent(plan.planKey)}`); }} className="mt-7 w-full rounded-2xl bg-gradient-to-r from-cyan-500 to-blue-600 px-5 py-3.5 text-sm font-black">Choose {plan.name}</button></div>; })}</div></section>
      </main>
      <footer className="border-t border-white/10 px-5 py-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 sm:flex-row"><div><p className="font-black">EduSphere</p><p className="mt-1 text-sm text-slate-500">Multi-school management, subscriptions and operations.</p></div><p className="text-sm text-slate-600">© {new Date().getFullYear()} EduSphere</p></div></footer>
      <SchoolSearchModal isOpen={searchOpen} onClose={() => setSearchOpen(false)} />
    </div>
  );
}
