import React, { useEffect, useMemo, useState } from 'react';
import { Download, FileBarChart2, Loader2, RefreshCw, Users } from 'lucide-react';
import apiClient from '@/api/apiClient';
import { toast } from 'sonner';

type Stats = { students?: number; teachers?: number; staff?: number; parents?: number; classes?: number; sections?: number; };
type Payment = { amount?: number; status?: string; paidAt?: string; createdAt?: string };
type Exam = { id: string; name: string; type: string; startDate: string; totalMarks: number; passingMarks: number };

export default function Reports() {
  const [stats, setStats] = useState<Stats>({}); const [payments, setPayments] = useState<Payment[]>([]); const [exams, setExams] = useState<Exam[]>([]); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const [s, p, e] = await Promise.all([apiClient.get('/people/stats'), apiClient.get('/finance/payments'), apiClient.get('/exams')]); setStats(s.data || {}); setPayments(Array.isArray(p.data) ? p.data : []); setExams(Array.isArray(e.data) ? e.data : []); } catch (e: any) { toast.error(e?.response?.data?.message || 'Unable to load report data'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const collected = useMemo(() => payments.filter(p => String(p.status || '').toUpperCase() === 'PAID').reduce((n, p) => n + Number(p.amount || 0), 0), [payments]);
  const pending = useMemo(() => payments.filter(p => String(p.status || '').toUpperCase() !== 'PAID').reduce((n, p) => n + Number(p.amount || 0), 0), [payments]);
  const exportCsv = () => { const rows = [['Metric','Value'], ...Object.entries(stats).map(([k,v]) => [k,String(v ?? 0)]), ['Payments', String(payments.length)], ['Collected PKR', String(collected)], ['Outstanding PKR', String(pending)], ['Exams', String(exams.length)]]; const csv = rows.map(r => r.map(v => `"${v.replace(/"/g,'""')}"`).join(',')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = `school-report-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(a.href); toast.success('Report exported'); };
  if (loading) return <div className="py-16 flex justify-center"><Loader2 className="animate-spin"/></div>;
  const cards = [['Students', stats.students ?? 0], ['Teachers', stats.teachers ?? 0], ['Staff', stats.staff ?? 0], ['Parents', stats.parents ?? 0], ['Classes', stats.classes ?? 0], ['Sections', stats.sections ?? 0]];
  return <div className="space-y-6"><div className="flex flex-col md:flex-row md:justify-between gap-4"><div><h1 className="text-2xl font-bold">Reports</h1><p className="text-sm text-muted-foreground">Live operational reports generated from school data.</p></div><div className="flex gap-2"><button onClick={load} className="px-4 py-2 rounded-lg border flex items-center gap-2"><RefreshCw size={16}/> Refresh</button><button onClick={exportCsv} className="px-4 py-2 rounded-lg bg-primary text-primary-foreground flex items-center gap-2"><Download size={16}/> Export CSV</button></div></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">{cards.map(([label,value]) => <div key={String(label)} className="rounded-xl border p-4"><div className="text-2xl font-bold">{String(value)}</div><div className="text-xs text-muted-foreground">{label}</div></div>)}</div><div className="grid md:grid-cols-2 gap-4"><div className="rounded-xl border p-5"><h2 className="font-semibold flex items-center gap-2"><FileBarChart2 size={18}/> Finance summary</h2><div className="mt-4 space-y-3"><div className="flex justify-between"><span>Payment records</span><b>{payments.length}</b></div><div className="flex justify-between"><span>Collected</span><b>PKR {collected.toLocaleString()}</b></div><div className="flex justify-between"><span>Outstanding / non-paid records</span><b>PKR {pending.toLocaleString()}</b></div></div></div><div className="rounded-xl border p-5"><h2 className="font-semibold flex items-center gap-2"><Users size={18}/> Examination summary</h2><div className="mt-4 space-y-2">{exams.length === 0 ? <p className="text-sm text-muted-foreground">No exams created yet.</p> : exams.slice(0,8).map(e => <div key={e.id} className="flex justify-between border-b last:border-0 py-2"><span>{e.name}</span><span className="text-xs text-muted-foreground">{e.type} · {e.totalMarks} marks</span></div>)}</div></div></div></div>;
}
