import React, { useEffect, useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Plus, Trash2, GraduationCap, X, Loader2, Search,
  User, Shield, FileSpreadsheet, FileText, Printer, ArrowUpRight,
  MapPin, Phone, Mail, FileDown, Upload, Check, CheckCircle, AlertCircle, Calendar, CreditCard, Award, BookOpen, UserCheck, ShieldAlert, ShieldCheck, Edit2, Save, Users, UserPlus, Fingerprint, Copy
} from 'lucide-react';
import apiClient from '@/api/apiClient';
import { toast } from 'sonner';
import Modal, { ModalHeader } from '@/component/ui/Modal';
import { useAuth } from '@/context/AuthContext';

// Existing Students page logic/data is preserved below.
// Student credentials are now generated by the backend; this helper only presents them once.
type StudentCredentials = { loginId: string; password: string };

// ...
