import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Archive, BookOpen, Check, Edit2, FileDown, GraduationCap, Loader2, Plus, Printer, RotateCcw, Search, Trash2, User, Users, X } from 'lucide-react';
import apiClient from '@/api/apiClient';
import { toast } from 'sonner';
import Modal, { ModalHeader } from '@/component/ui/Modal';
import { useAuth } from '@/context/AuthContext';

type Student = { id:string; name:string; email?:string; admissionNo:string; rollNo?:string|number; gender?:string; dateOfBirth?:string; session?:string; status?:string; phone?:string; bFormNumber?:string; avatarUrl?:string; sectionId?:string; section?:{id?:string;name?:string;classId?:string;class?:{id?:string;name?:string}}; [key:string]:any };
type Section = { id:string; name:string; classId?:string; class?:{id:string;name:string}; capacity?:number };
type SchoolClass = { id:string; name:string; sections?:Section[] };
const emptyForm:any={name:'',email:'',studentMobile:'',gender:'MALE',dateOfBirth:'',bloodGroup:'',religion:'',bFormNumber:'',sectionId:'',session:'2026-2027',status:'ACTIVE',fatherName:'',fatherMobile1:'',fatherCnic:'',motherName:'',motherMobile:'',guardianName:'',guardianMobile:'',country:'Pakistan',province:'Punjab',city:'',currentAddress:'',permanentAddress:'',emergencyContact:'',previousSchool:'',previousClass:'',admissionType:'NEW',remarks:'',transportRequired:false,hostelRequired:false};
const input='w-full rounded-xl border border-white/[0.08] bg-slate-900/60 px-3 py-2.5 text-sm text-white outline-none focus:border-primary';

export default function Students(){
 const {user,previewRole}=useAuth(); const role=previewRole??user?.role; const canManage=role==='SCHOOL_ADMIN';
 const [students,setStudents]=useState<Student[]>([]),[archived,setArchived]=useState<Student[]>([]),[classes,setClasses]=useState<SchoolClass[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[classId,setClassId]=useState(''),[sectionId,setSectionId]=useState(''),[showArchived,setShowArchived]=useState(false),[selectedIds,setSelectedIds]=useState<string[]>([]),[selected,setSelected]=useState<Student|null>(null),[profile,setProfile]=useState<any>(null),[profileLoading,setProfileLoading]=useState(false),[tab,setTab]=useState('overview'),[modal,setModal]=useState<'add'|'edit'|'promote'|'transfer'|null>(null),[saving,setSaving]=useState(false),[form,setForm]=useState<any>(emptyForm),[target,setTarget]=useState(''),[reason,setReason]=useState('');
 const sections=useMemo(()=>classes.flatMap(c=>(c.sections||[]).map(s=>({...s,classId:s.classId||c.id,class:s.class||{id:c.id,name:c.name}}))),[classes]);
 const load=useCallback(async()=>{setLoading(true);try{const [a,b]=await Promise.all([apiClient.get('/people/students'),apiClient.get('/classes')]);setStudents(Array.isArray(a.data)?a.data:[]);setClasses(Array.isArray(b.data)?b.data:[]);}catch(e:any){setStudents([]);setClasses([]);toast.error(e?.response?.data?.message||'Unable to load students')}finally{setLoading(false)}},[]);
 const loadArchived=useCallback(async()=>{if(!canManage)return;try{const r=await apiClient.get('/people/students/archived');setArchived(Array.isArray(r.data)?r.data:[])}catch(e:any){toast.error(e?.response?.data?.message||'Unable to load archived students')}},[canManage]);
 useEffect(()=>{load()},[load]); useEffect(()=>{if(showArchived)loadArchived()},[showArchived,loadArchived]);
 const visible=useMemo(()=>{const source=showArchived?archived:students,q=search.trim().toLowerCase();return source.filter(s=>{const hay=[s.name,s.admissionNo,s.rollNo,s.email,s.section?.name,s.section?.class?.name].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!status||s.status===status)&&(!classId||s.section?.class?.id===classId||s.section?.classId===classId)&&(!sectionId||s.sectionId===sectionId||s.section?.id===sectionId)})},[students,archived,showArchived,search,status,classId,sectionId]);
 const refresh=async()=>{await load();if(showArchived)await loadArchived()};
 const openProfile=async(s:Student)=>{setSelected(s);setProfile(null);setTab('overview');setProfileLoading(true);try{const r=await apiClient.get(`/people/students/${s.id}/profile`);setProfile(r.data)}catch(e:any){toast.error(e?.response?.data?.message||'Unable to load profile')}finally{setProfileLoading(false)}};
 const add=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{await apiClient.post('/people/students',{...form,phone:form.studentMobile,address:form.currentAddress,addressCountry:form.country,addressProvince:form.province,addressCity:form.city,addressLine:form.currentAddress,password:'student123',parentPassword:crypto.randomUUID().slice(0,8)});toast.success('Student added successfully');setModal(null);setForm(emptyForm);await refresh()}catch(e:any){toast.error(e?.response?.data?.message||'Failed to add student')}finally{setSaving(false)}};
 const edit=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;setSaving(true);try{await apiClient.patch(`/people/students/${selected.id}/full`,form);toast.success('Student profile updated');setModal(null);await refresh();await openProfile({...selected,...form})}catch(e:any){toast.error(e?.response?.data?.message||'Failed to update student')}finally{setSaving(false)}};
 const archive=async(id:string)=>{if(!confirm('Archive this student? The record will remain in the system.'))return;try{await apiClient.delete(`/people/students/${id}`);toast.success('Student archived');await refresh()}catch(e:any){toast.error(e?.response?.data?.message||'Failed to archive student')}};
 const restore=async(id:string)=>{try{await apiClient.post(`/people/students/${id}/restore`);toast.success('Student restored');await refresh()}catch(e:any){toast.error(e?.response?.data?.message||'Failed to restore student')}};
 const promote=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedIds.length||!target)return toast.warning('Select students and a target section');setSaving(true);try{await apiClient.post('/people/students/promote',{studentIds:selectedIds,sectionId:target,session:form.session||undefined});toast.success(`${selectedIds.length} student(s) promoted`);setModal(null);setSelectedIds([]);await refresh()}catch(e:any){toast.error(e?.response?.data?.message||'Promotion failed')}finally{setSaving(false)}};
 const transfer=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedIds.length||!target)return toast.warning('Select students and a target section');setSaving(true);try{await apiClient.post('/people/students/transfer',{studentIds:selectedIds,sectionId:target,reason});toast.success(`${selectedIds.length} student(s) transferred`);setModal(null);setSelectedIds([]);setReason('');await refresh()}catch(e:any){toast.error(e?.response?.data?.message||'Transfer failed')}finally{setSaving(false)}};
 const exportExcel=()=>{const rows=visible.map(s=>[s.admissionNo,s.rollNo??'',s.name,s.email??'',s.phone??'',s.section?.class?.name??'',s.section?.name??'',s.session??'',s.status??'']);const csv=[['Admission No','Roll No','Name','Email','Phone','Class','Section','Session','Status'],...rows].map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`edusphere-students-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);toast.success('Excel-compatible CSV exported')};
 const print=()=>{const rows=visible.map(s=>`<tr><td>${s.admissionNo}</td><td>${s.rollNo??''}</td><td>${s.name}</td><td>${s.section?.class?.name??''} - ${s.section?.name??''}</td><td>${s.status??''}</td></tr>`).join('');const w=window.open('','_blank','width=1000,height=700');if(!w)return toast.error('Popup blocked. Allow popups to print.');w.document.write(`<html><head><title>EduSphere Students</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:8px;text-align:left}</style></head><body><h1>EduSphere — Student Report</h1><p>${new Date().toLocaleDateString()}</p><table><thead><tr><th>Admission</th><th>Roll</th><th>Name</th><th>Class / Section</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()};
 const beginEdit=(s:Student)=>{setSelected(s);setForm({...emptyForm,...s,studentMobile:s.phone||'',sectionId:s.sectionId||s.section?.id||'',currentAddress:s.currentAddress||s.address||''});setModal('edit')};
 const toggle=(id:string)=>setSelectedIds(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]); const all=()=>setSelectedIds(selectedIds.length===visible.length?[]:visible.map(s=>s.id));
 return <div className="space-y-5 pb-10"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.3em] text-primary">People Management</p><h1 className="mt-1 text-2xl font-black text-white">Students</h1><p className="text-xs text-slate-500">Real school records and tenant-isolated academic actions.</p></div>{canManage&&<button onClick={()=>{setForm(emptyForm);setModal('add')}} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-xs font-black uppercase tracking-widest text-white"><Plus size={15}/>Add Student</button>}</div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Active" value={students.length}/><Stat label="Archived" value={archived.length}/><Stat label="Selected" value={selectedIds.length}/><Stat label="Visible" value={visible.length}/></div>
 <div className="rounded-2xl border border-white/[0.07] bg-white/[0.02] p-3"><div className="flex flex-col gap-2 xl:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-600" size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, admission, roll, class..." className={`${input} pl-9`}/></div><select value={classId} onChange={e=>{setClassId(e.target.value);setSectionId('')}} className={input}><option value="">All Classes</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={sectionId} onChange={e=>setSectionId(e.target.value)} className={input}><option value="">All Sections</option>{sections.filter(s=>!classId||s.classId===classId).map(s=><option key={s.id} value={s.id}>{s.class?.name} — {s.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className={input}><option value="">All Status</option><option>ACTIVE</option><option>INACTIVE</option><option>LEFT</option><option>GRADUATED</option></select></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setShowArchived(v=>!v)} className="rounded-lg border border-white/[0.08] px-3 py-2 text-[10px] font-black uppercase tracking-widest text-slate-300">{showArchived?'Active Students':'Archived Students'}</button>{canManage&&!showArchived&&selectedIds.length>0&&<><button onClick={()=>{setTarget('');setModal('promote')}} className="rounded-lg bg-primary/10 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-primary">Promote</button><button onClick={()=>{setTarget('');setModal('transfer')}} className="rounded-lg bg-violet-500/10 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-violet-300">Transfer</button></>}<div className="ml-auto flex gap-2"><button onClick={exportExcel} title="Excel-compatible export" className="rounded-lg border border-white/[0.08] p-2 text-slate-300"><FileDown size={15}/></button><button onClick={print} title="Print / Save PDF" className="rounded-lg border border-white/[0.08] p-2 text-slate-300"><Printer size={15}/></button></div></div></div>
 <div className="overflow-hidden rounded-2xl border border-white/[0.07] bg-white/[0.02]"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b border-white/[0.06] text-[9px] font-black uppercase tracking-widest text-slate-600"><th className="px-4 py-3"><input type="checkbox" checked={visible.length>0&&selectedIds.length===visible.length} onChange={all}/></th><th className="px-4 py-3">Student</th><th className="px-4 py-3">Admission</th><th className="px-4 py-3">Class</th><th className="px-4 py-3">Roll</th><th className="px-4 py-3">Session</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={8} className="py-16 text-center"><Loader2 className="mx-auto animate-spin text-primary"/></td></tr>:visible.length===0?<tr><td colSpan={8} className="py-16 text-center text-xs text-slate-600">No student records found.</td></tr>:visible.map(s=><tr key={s.id} className="border-b border-white/[0.04] hover:bg-white/[0.025]"><td className="px-4 py-3"><input type="checkbox" checked={selectedIds.includes(s.id)} onChange={()=>toggle(s.id)}/></td><td className="px-4 py-3"><button onClick={()=>openProfile(s)} className="flex items-center gap-3 text-left"><div className="h-9 w-9 overflow-hidden rounded-xl bg-primary/10 flex items-center justify-center text-primary font-black">{s.avatarUrl?<img src={s.avatarUrl} className="h-full w-full object-cover"/>:<User size={16}/>}</div><div><div className="text-sm font-bold text-white">{s.name}</div><div className="text-[10px] text-slate-600">{s.email||'No email'}</div></div></button></td><td className="px-4 py-3 font-mono text-xs text-slate-300">{s.admissionNo}</td><td className="px-4 py-3 text-xs text-slate-300">{s.section?.class?.name||'—'} / {s.section?.name||'—'}</td><td className="px-4 py-3 text-xs text-slate-300">{s.rollNo||'—'}</td><td className="px-4 py-3 text-xs text-slate-400">{s.session||'—'}</td><td className="px-4 py-3"><span className="rounded-full bg-white/[0.05] px-2 py-1 text-[9px] font-black uppercase text-slate-300">{s.status||'ACTIVE'}</span></td><td className="px-4 py-3 text-right"><div className="flex justify-end gap-1">{canManage&&!showArchived&&<><button onClick={()=>beginEdit(s)} className="rounded-lg p-2 text-slate-400 hover:text-primary"><Edit2 size={14}/></button><button onClick={()=>archive(s.id)} className="rounded-lg p-2 text-slate-400 hover:text-rose-400"><Trash2 size={14}/></button></>}{canManage&&showArchived&&<button onClick={()=>restore(s.id)} className="rounded-lg p-2 text-slate-400 hover:text-emerald-400"><RotateCcw size={14}/></button>}</div></td></tr>)}</tbody></table></div></div>
 {modal==='add'&&<StudentModal title="Add Student" form={form} setForm={setForm} sections={sections} saving={saving} close={()=>setModal(null)} submit={add}/>} {modal==='edit'&&<StudentModal title="Edit Student" form={form} setForm={setForm} sections={sections} saving={saving} close={()=>setModal(null)} submit={edit}/>} {modal==='promote'&&<ActionModal title="Promote Students" sections={sections} target={target} setTarget={setTarget} saving={saving} close={()=>setModal(null)} submit={promote}>{selectedIds.length} student(s) selected.</ActionModal>} {modal==='transfer'&&<ActionModal title="Transfer Students" sections={sections} target={target} setTarget={setTarget} saving={saving} close={()=>setModal(null)} submit={transfer}><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Transfer reason (optional)" className={`${input} min-h-24 mt-3`}/></ActionModal>}
 {selected&&<Modal open={true} onClose={()=>setSelected(null)}><ModalHeader title={selected.name} onClose={()=>setSelected(null)}/><div className="p-5">{profileLoading?<Loader2 className="mx-auto animate-spin text-primary"/>:profile&&<><div className="flex items-center gap-4 border-b border-white/[0.06] pb-4"><div className="h-16 w-16 overflow-hidden rounded-2xl bg-primary/10 flex items-center justify-center">{profile.avatarUrl?<img src={profile.avatarUrl} className="h-full w-full object-cover"/>:<User size={24} className="text-primary"/>}</div><div><h3 className="font-black text-white">{profile.name}</h3><p className="text-xs text-slate-500">{profile.admissionNo} · Roll {profile.rollNo||'—'}</p></div></div><div className="my-4 flex flex-wrap gap-2">{['overview','attendance','fees','results','homework'].map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-lg px-3 py-2 text-[9px] font-black uppercase tracking-widest ${tab===t?'bg-primary text-white':'bg-white/[0.04] text-slate-500'}`}>{t}</button>)}</div><Profile tab={tab} p={profile}/></>}</div></Modal>}
 </div>
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-4"><div className="text-xl font-black text-white">{value}</div><div className="text-[9px] font-black uppercase tracking-widest text-slate-600">{label}</div></div>}
function StudentModal({title,form,setForm,sections,saving,close,submit}:{title:string;form:any;setForm:(f:any)=>void;sections:Section[];saving:boolean;close:()=>void;submit:(e:React.FormEvent)=>void}){const set=(k:string,v:any)=>setForm((p:any)=>({...p,[k]:v}));return <Modal open={true} onClose={close}><ModalHeader title={title} onClose={close}/><form onSubmit={submit} className="max-h-[78vh] overflow-y-auto p-5"><div className="grid grid-cols-1 gap-3 md:grid-cols-2">{[['name','Student Name *'],['email','Email *'],['studentMobile','Mobile'],['dateOfBirth','Date of Birth'],['bFormNumber','B-Form / CNIC'],['fatherName','Father Name'],['fatherMobile1','Father Mobile'],['motherName','Mother Name'],['motherMobile','Mother Mobile'],['city','City'],['currentAddress','Current Address'],['permanentAddress','Permanent Address']].map(([k,l])=><Field key={k} label={l}><input required={k==='name'||k==='email'} type={k==='dateOfBirth'?'date':'text'} value={form[k]||''} onChange={e=>set(k,e.target.value)} className={input}/></Field>)}<Field label="Gender"><select value={form.gender||'MALE'} onChange={e=>set('gender',e.target.value)} className={input}><option>MALE</option><option>FEMALE</option><option>OTHER</option></select></Field><Field label="Section *"><select required value={form.sectionId||''} onChange={e=>set('sectionId',e.target.value)} className={input}><option value="">Select section</option>{sections.map(s=><option key={s.id} value={s.id}>{s.class?.name} — {s.name}</option>)}</select></Field><Field label="Session"><input value={form.session||''} onChange={e=>set('session',e.target.value)} className={input}/></Field><Field label="Status"><select value={form.status||'ACTIVE'} onChange={e=>set('status',e.target.value)} className={input}><option>ACTIVE</option><option>INACTIVE</option><option>LEFT</option><option>GRADUATED</option></select></Field></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-xl border border-white/[0.08] px-4 py-2 text-xs text-slate-400">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 text-xs font-black text-white">{saving&&<Loader2 size={13} className="animate-spin"/>}<Check size={13}/>Save</button></div></form></Modal>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-1"><span className="ml-1 text-[9px] font-black uppercase tracking-widest text-slate-600">{label}</span>{children}</label>}
function ActionModal({title,sections,target,setTarget,saving,close,submit,children}:{title:string;sections:Section[];target:string;setTarget:(v:string)=>void;saving:boolean;close:()=>void;submit:(e:React.FormEvent)=>void;children:React.ReactNode}){return <Modal open={true} onClose={close}><ModalHeader title={title} onClose={close}/><form onSubmit={submit} className="p-5"><select required value={target} onChange={e=>setTarget(e.target.value)} className={input}><option value="">Select destination section</option>{sections.map(s=><option key={s.id} value={s.id}>{s.class?.name} — {s.name}</option>)}</select>{children}<div className="mt-4 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-xl border border-white/[0.08] px-4 py-2 text-xs text-slate-400">Cancel</button><button disabled={saving} className="rounded-xl bg-primary px-4 py-2 text-xs font-black text-white">{saving?'Processing...':'Confirm'}</button></div></form></Modal>}
function Profile({tab,p}:{tab:string;p:any}){if(tab==='attendance')return <List rows={p.attendances} fields={['date','status']}/>;if(tab==='fees')return <List rows={p.feePayments} fields={['amount','status','paidAt']}/>;if(tab==='results')return <List rows={p.examResults} fields={['exam.name','subject.name','marks','grade']}/>;if(tab==='homework')return <List rows={p.homeworkSubmissions} fields={['homework.title','status','submittedAt']}/>;const parent=p.parents?.[0]?.parent;return <div className="grid grid-cols-1 gap-3 md:grid-cols-2">{[['Class',p.section?.class?.name],['Section',p.section?.name],['Session',p.session],['DOB',p.dateOfBirth?new Date(p.dateOfBirth).toLocaleDateString():'—'],['Gender',p.gender],['Phone',p.phone],['B-Form/CNIC',p.bFormNumber],['Father',parent?.fatherName],['Father Mobile',parent?.fatherMobile1],['Mother',parent?.motherName],['Address',p.currentAddress||p.address]].map(([k,v])=><div key={String(k)} className="rounded-xl border border-white/[0.05] bg-white/[0.02] p-3"><div className="text-[9px] font-black uppercase tracking-widest text-slate-600">{k}</div><div className="mt-1 text-sm text-slate-300">{v||'—'}</div></div>)}</div>}
function List({rows,fields}:{rows:any[];fields:string[]}){if(!rows?.length)return <p className="py-8 text-center text-xs text-slate-600">No records available.</p>;return <div className="space-y-2">{rows.map((r,i)=><div key={r.id||i} className="grid grid-cols-2 gap-2 rounded-xl border border-white/[0.05] bg-white/[0.02] p-3 text-xs text-slate-400">{fields.map(f=><div key={f}><span className="text-[9px] uppercase text-slate-600">{f}</span><div className="mt-1">{f.split('.').reduce((o,k)=>o?.[k],r)??'—'}</div></div>)}</div>)}</div>}
