import React, { useEffect, useMemo, useState } from 'react';
import { BookOpen, Loader2, Users } from 'lucide-react';
import apiClient from '@/api/apiClient';
import { toast } from 'sonner';

type ClassItem = { id: string; name: string; sections: { id: string; name: string; capacity: number; teacher?: { id: string; name: string } | null }[] };
type Exam = { id: string; name: string; type: string; totalMarks: number; passingMarks: number };
type Subject = { id: string; name: string; code?: string | null };

export function MyClasses() {
  const [classes, setClasses] = useState<ClassItem[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { apiClient.get('/classes').then(r => setClasses(Array.isArray(r.data) ? r.data : [])).catch(e => toast.error(e?.response?.data?.message || 'Unable to load classes')).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="py-16 flex justify-center"><Loader2 className="animate-spin"/></div>;
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">My Classes</h1><p className="text-sm text-muted-foreground">Live classes and sections available to your school account.</p></div>{classes.length === 0 ? <div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">No classes available.</div> : <div className="grid md:grid-cols-2 gap-4">{classes.map(c => <div key={c.id} className="rounded-xl border p-5"><div className="flex items-center gap-2 mb-3"><BookOpen size={18}/><h2 className="font-semibold">{c.name}</h2></div>{(c.sections || []).length === 0 ? <p className="text-sm text-muted-foreground">No sections.</p> : <div className="space-y-2">{c.sections.map(s => <div key={s.id} className="rounded-lg bg-muted/40 p-3 flex justify-between"><span>{s.name}</span><span className="text-xs text-muted-foreground">Capacity {s.capacity}</span></div>)}</div>}</div>)}</div>}</div>;
}

export function Attendance() {
  const [classes, setClasses] = useState<ClassItem[]>([]); const [sectionId, setSectionId] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [records, setRecords] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { apiClient.get('/classes').then(r => { const list = Array.isArray(r.data) ? r.data : []; setClasses(list); const first = list.flatMap((c: ClassItem) => c.sections || [])[0]; if (first) setSectionId(first.id); }).catch(e => toast.error(e?.response?.data?.message || 'Unable to load sections')).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!sectionId) return; setLoading(true); apiClient.get(`/attendance/section/${sectionId}`, { params: { date } }).then(r => setRecords(Array.isArray(r.data) ? r.data : [])).catch(e => toast.error(e?.response?.data?.message || 'Unable to load attendance')).finally(() => setLoading(false)); }, [sectionId, date]);
  const sections = useMemo(() => classes.flatMap(c => (c.sections || []).map(s => ({ ...s, className: c.name }))), [classes]);
  const save = async () => { setSaving(true); try { await apiClient.post('/attendance/mark', { sectionId, date, records: records.map(r => ({ studentId: r.studentId, status: r.status, remarks: r.remarks || undefined })) }); toast.success('Attendance saved'); } catch (e: any) { toast.error(e?.response?.data?.message || 'Could not save attendance'); } finally { setSaving(false); } };
  if (loading && !records.length) return <div className="py-16 flex justify-center"><Loader2 className="animate-spin"/></div>;
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Attendance</h1><p className="text-sm text-muted-foreground">Mark attendance using live student records.</p></div><div className="rounded-xl border p-4 flex flex-col md:flex-row gap-3"><select className="rounded-lg border p-3 bg-background flex-1" value={sectionId} onChange={e => setSectionId(e.target.value)}><option value="">Select section</option>{sections.map(s => <option key={s.id} value={s.id}>{s.className} / {s.name}</option>)}</select><input type="date" className="rounded-lg border p-3 bg-background" value={date} onChange={e => setDate(e.target.value)}/><button onClick={save} disabled={saving || !records.length} className="rounded-lg bg-primary text-primary-foreground px-4">{saving ? 'Saving...' : 'Save'}</button></div>{records.length === 0 ? <div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground"><Users className="mx-auto mb-2"/>No students found.</div> : <div className="rounded-xl border overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Roll</th><th className="p-3">Student</th><th className="p-3">Status</th></tr></thead><tbody>{records.map(r => <tr key={r.studentId} className="border-b"><td className="p-3">{r.rollNo || '—'}</td><td className="p-3">{r.name}</td><td className="p-3"><select className="rounded border p-2 bg-background" value={r.status} onChange={e => setRecords(prev => prev.map(x => x.studentId === r.studentId ? { ...x, status: e.target.value } : x))}><option>PRESENT</option><option>ABSENT</option><option>LATE</option><option>LEAVE</option></select></td></tr>)}</tbody></table></div>}</div>;
}

export function Grades() {
  const [exams, setExams] = useState<Exam[]>([]); const [subjects, setSubjects] = useState<Subject[]>([]); const [examId, setExamId] = useState(''); const [subjectId, setSubjectId] = useState(''); const [results, setResults] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([apiClient.get('/exams'), apiClient.get('/classes/subjects')]).then(([e, s]) => { setExams(Array.isArray(e.data) ? e.data : []); setSubjects(Array.isArray(s.data) ? s.data : []); }).catch(e => toast.error(e?.response?.data?.message || 'Unable to load grades data')).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!examId || !subjectId) { setResults([]); return; } apiClient.get('/exams/results', { params: { examId, subjectId } }).then(r => setResults(Array.isArray(r.data) ? r.data : [])).catch(e => toast.error(e?.response?.data?.message || 'Unable to load results')); }, [examId, subjectId]);
  if (loading) return <div className="py-16 flex justify-center"><Loader2 className="animate-spin"/></div>;
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Grades</h1><p className="text-sm text-muted-foreground">View published results from the examination system.</p></div><div className="rounded-xl border p-4 grid md:grid-cols-2 gap-3"><select className="rounded-lg border p-3 bg-background" value={examId} onChange={e => setExamId(e.target.value)}><option value="">Select exam</option>{exams.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select><select className="rounded-lg border p-3 bg-background" value={subjectId} onChange={e => setSubjectId(e.target.value)}><option value="">Select subject</option>{subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{!examId || !subjectId ? <div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">Select an exam and subject to view results.</div> : results.length === 0 ? <div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">No results recorded for this selection.</div> : <div className="rounded-xl border overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Student</th><th className="p-3">Roll</th><th className="p-3">Marks</th><th className="p-3">Grade</th><th className="p-3">Status</th></tr></thead><tbody>{results.map(r => <tr key={r.id} className="border-b"><td className="p-3">{r.student?.name || '—'}</td><td className="p-3">{r.student?.rollNo || '—'}</td><td className="p-3">{r.isAbsent ? 'Absent' : r.marksObtained}</td><td className="p-3">{r.grade || '—'}</td><td className="p-3">{r.isAbsent ? 'ABSENT' : 'PRESENT'}</td></tr>)}</tbody></table></div>}</div>;
}
