import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Loader2, Plus, RefreshCw, Trash2, X } from 'lucide-react';
import apiClient from '@/api/apiClient';
import { useAuth } from '@/context/AuthContext';
import { toast } from 'sonner';

type Section={id:string;name:string;class?:{name?:string}};
type Subject={id:string;name:string};
type Teacher={id:string;name:string;email?:string};
type Slot={id:string;dayOfWeek:number;startTime:string;endTime:string;room?:string|null;section?:Section;subject?:Subject;teacher?:Teacher;sectionId?:string;subjectId?:string;teacherId?:string};
const days=[['1','Monday'],['2','Tuesday'],['3','Wednesday'],['4','Thursday'],['5','Friday'],['6','Saturday']];
export default function TimetableLive(){
 const {user}=useAuth(); const canEdit=user?.role==='SCHOOL_ADMIN'||user?.role==='TEACHER';
 const [slots,setSlots]=useState<Slot[]>([]),[sections,setSections]=useState<Section[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[teachers,setTeachers]=useState<Teacher[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[day,setDay]=useState(1),[section,setSection]=useState('');
 const [form,setForm]=useState({dayOfWeek:'1',startTime:'08:00',endTime:'08:45',room:'',sectionId:'',subjectId:'',teacherId:''});
 const load=async()=>{try{const [t,classRes,sub,tr]=await Promise.all([apiClient.get('/academics/timetables'),apiClient.get('/classes'),apiClient.get('/classes/subjects'),apiClient.get('/people/teachers')]);const classes=Array.isArray(classRes.data)?classRes.data:[];setSlots(Array.isArray(t.data)?t.data:[]);setSections(classes.flatMap((item:any)=>(item.sections||[]).map((itemSection:any)=>({...itemSection,class:{name:item.name}}))));setSubjects(Array.isArray(sub.data)?sub.data:[]);setTeachers(Array.isArray(tr.data)?tr.data:[])}catch(e:any){toast.error(e?.response?.data?.message||'Unable to load timetable')}finally{setLoading(false);setRefreshing(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>slots.filter(s=>(!section||s.sectionId===section)&&s.dayOfWeek===day).sort((a,b)=>a.startTime.localeCompare(b.startTime)),[slots,section,day]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const {data}=await apiClient.post('/academics/timetables',{...form,dayOfWeek:Number(form.dayOfWeek)});setSlots(p=>[...p,data]);setShow(false);toast.success('Timetable entry added');setForm({dayOfWeek:String(day),startTime:'08:00',endTime:'08:45',room:'',sectionId:section,subjectId:'',teacherId:''})}catch(e:any){toast.error(e?.response?.data?.message||'Failed to add timetable entry')}finally{setSaving(false)}};
 const remove=async(id:string)=>{if(!confirm('Delete this timetable entry?'))return;try{await apiClient.delete(`/academics/timetables/${id}`);setSlots(p=>p.filter(x=>x.id!==id));toast.success('Entry deleted')}catch(e:any){toast.error(e?.response?.data?.message||'Unable to delete entry')}};
 if(loading)return <div className="min-h-[50vh] flex items-center justify-center"><Loader2 className="animate-spin text-primary"/></div>;
 return <div className="space-y-6 pb-10"><div className="rounded-[28px] border border-border bg-card p-6 shadow-xl"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-primary">Academic Management</div><h1 className="text-3xl font-black mt-2">Timetable</h1><p className="text-sm text-muted-foreground mt-1">Live class schedules from the school database.</p></div><div className="flex gap-2"><button onClick={()=>{setRefreshing(true);load()}} className="rounded-xl border border-border px-4 py-2.5 text-sm font-bold"><RefreshCw size={16} className="inline mr-2"/>Refresh</button>{canEdit&&<button onClick={()=>{setForm(p=>({...p,dayOfWeek:String(day),sectionId:section}));setShow(true)}} className="rounded-xl bg-primary text-primary-foreground px-4 py-2.5 text-sm font-bold"><Plus size={16} className="inline mr-2"/>Add Period</button>}</div></div></div>
 <div className="grid lg:grid-cols-[1fr_2fr] gap-4"><div className="space-y-3"><select value={section} onChange={e=>setSection(e.target.value)} className="w-full rounded-xl border border-border bg-card px-4 py-3 text-sm"><option value="">All Sections</option>{sections.map(s=><option key={s.id} value={s.id}>{s.class?.name?`${s.class.name} • `:''}{s.name}</option>)}</select><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-1 gap-2">{days.map(([n,name])=><button key={n} onClick={()=>setDay(Number(n))} className={`rounded-xl border p-3 text-left text-sm font-bold ${day===Number(n)?'border-primary bg-primary/10 text-primary':'border-border bg-card'}`}><CalendarDays size={15} className="inline mr-2"/>{name}</button>)}</div></div><div className="rounded-3xl border border-border bg-card p-5 min-h-[420px]"><div className="mb-4 flex items-center justify-between"><h2 className="font-black text-xl">{days.find(d=>Number(d[0])===day)?.[1]}</h2><span className="text-xs text-muted-foreground">{visible.length} periods</span></div>{visible.length?<div className="space-y-3">{visible.map(s=><div key={s.id} className="rounded-2xl border border-border bg-background p-4 flex gap-4 items-center"><div className="w-28 shrink-0"><p className="font-black text-sm">{s.startTime} – {s.endTime}</p><p className="text-[11px] text-muted-foreground">{s.room||'No room'}</p></div><div className="flex-1"><p className="font-black">{s.subject?.name||'Subject'}</p><p className="text-xs text-muted-foreground">{s.section?.class?.name?`${s.section.class.name} • `:''}{s.section?.name||'Section'} • {s.teacher?.name||'Teacher'}</p></div>{canEdit&&<button onClick={()=>remove(s.id)} className="rounded-lg p-2 text-red-500 hover:bg-red-500/10"><Trash2 size={16}/></button>}</div>)}</div>:<div className="h-72 flex items-center justify-center text-sm text-muted-foreground">No timetable entries for this day.</div>}</div></div>
 {show&&<div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm p-4 flex items-center justify-center"><form onSubmit={create} className="w-full max-w-2xl rounded-3xl border border-border bg-card p-6 space-y-4"><div className="flex justify-between"><h2 className="text-xl font-black">Add Timetable Period</h2><button type="button" onClick={()=>setShow(false)}><X/></button></div><div className="grid sm:grid-cols-2 gap-3"><select required value={form.dayOfWeek} onChange={e=>setForm(p=>({...p,dayOfWeek:e.target.value}))} className="rounded-xl border border-border bg-background px-3 py-3">{days.map(([n,name])=><option key={n} value={n}>{name}</option>)}</select><select required value={form.sectionId} onChange={e=>setForm(p=>({...p,sectionId:e.target.value}))} className="rounded-xl border border-border bg-background px-3 py-3"><option value="">Select section</option>{sections.map(s=><option key={s.id} value={s.id}>{s.class?.name?`${s.class.name} • `:''}{s.name}</option>)}</select><select required value={form.subjectId} onChange={e=>setForm(p=>({...p,subjectId:e.target.value}))} className="rounded-xl border border-border bg-background px-3 py-3"><option value="">Select subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select required value={form.teacherId} onChange={e=>setForm(p=>({...p,teacherId:e.target.value}))} className="rounded-xl border border-border bg-background px-3 py-3"><option value="">Select teacher</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input required type="time" value={form.startTime} onChange={e=>setForm(p=>({...p,startTime:e.target.value}))} className="rounded-xl border border-border bg-background px-3 py-3"/><input required type="time" value={form.endTime} onChange={e=>setForm(p=>({...p,endTime:e.target.value}))} className="rounded-xl border border-border bg-background px-3 py-3"/><input placeholder="Room (optional)" value={form.room} onChange={e=>setForm(p=>({...p,room:e.target.value}))} className="rounded-xl border border-border bg-background px-3 py-3 sm:col-span-2"/></div><button disabled={saving} className="w-full rounded-xl bg-primary text-primary-foreground py-3 font-black">{saving?'Saving...':'Add Period'}</button></form></div>}</div>;
}
